language: java
jdk:
    - oraclejdk8

install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  webhooks:
    secure: "gOEI0Tm+Uy4TnULXZIFV3LBPON60IB77h54kgiSZpHkBR5VBne5NuF55mYBSHmHuLOg9v2jnumurz5uCg7UuGrQn00/Jg1Sbk76OCuEsMFKOBBf2bxClRrfNSK2/YsdkhTfRLBNDgws0aFKfWxP99IjtguXLDU90FewN599KA8nVLkcl5dzYu7lihIk0g58WLCc3yvM34X8rAKv44KX7xOcH8U2szA8yZFgX0qN9N1ycGZ5NAxro1X+JBy6xyPnQY8AcMlTx71pBWvzCqslgIUpco0hOiuYKuT+2kUGrPTrG8OF9ZElc2UbKVB22INr99vC7TBn6DVZGEJBWUL0Yey5whmKX8/SFLCSE2/HAbfWo/nCKbkcXpllAJzGYUUifN435ofnQ/opJPwf30QJQrBL9E7f5WaCcInStjUXdMNIXnvBf/QZJjLBWU3pU41g76KCUyQwOi0CTvK8R0mH77u6bsi0m2t8NIraCzHuxksGElQ4l2MpZVlsvGHdp3o14EKgzO89+H6Tci7k2xII/CnxX2Joujux502azG371HicpP2x9vzF7I2ZZqQscN7YOzc4JtcAeUPrdX+OysgR/Ggf3XL2IxLUE1CgqsdaIBsjfJMxL2Gk5zgebzRNa8sn4guY6NdXHPnNPq1i6OEFAnCBrywEQmWfclUlfWCi9IdY="