language: java
jdk:
    - oraclejdk8

install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  webhooks:
    secure: "D2H0ZO3FVGHBp4VlWgX3F2OuKWc2dTxfQ08UqOeQ56bb7TT5Kyes2HYQrER9AvvTD6Lg76R0043UWOsVBWhlOJY7Hd/shJbpysFHJRqNK9u1GUziZ+cBIkfHcPgxucKDKNH/MhSHczt60ptCTO1iAnMvGFgFCVu1vhI75hEyqMoUzq0sOshjjAYCeFkMmDJ09xXKcdflHQPiSRDqRfclD/+dct7ScmhpQHJjTYassThPG9cIwrAmcKqQR4c3PqlxbSDAg/b+S7+SbEbmgf0B9yYH+BF6giquasttDMuDJQHcOB0SsGxhw2VLqRXuUzNm4LQnwE2QULyoOXAYilTCbIzKDofDgoM0axssHNYqXQ4PVTxB+O5Nt1PFbkMHrO0Nh0HsQr71QzCx61xYpZ8lgobDn3KFnXlsnEEHnalG+83+cjv55DMMtXBsEPoYwwKq5wP2kFk+SqWqBEAcRX8kT6Ulv8i09nCJtF9//mYykZ0qepyVwOdmC/tmTtfs93qJMr/vDXXwA8MLyo3b5hJlocawGe4z9+rkFtw7qfH3zppkmFDFXo+/iNT237EGx4WYsfo79Rnn/2yFPg2guoH3LJYYNT4TC0TQuYJwcMYff4Q14MvsNt3XzR8a2dWB3AhdUyqWhXDmTZTuQN3pKpsIwYKdAHxpssjb5Yqrm+4o9dg="